DIR_PIN_KIT:  '~/project/IgorWork/SonicTracer/PinKit'
DIR_PIN_TOOL: '~/project/IgorWork/SonicTracer/PinTool'
DIR_PIN_LOG:  '~/project/IgorWork/SonicTracer/PinKit'
DIR_FALLBACK: '/tmp'

BIN_nm: '/usr/bin/nm'
BIN_readelf: '/usr/bin/readelf'
BIN_addr2line: '/usr/bin/addr2line'
BIN_llvm-symbolizer: '/usr/lib/llvm-10/bin/llvm-symbolizer'