DIR_PIN_KIT:  '~/project/IgorWork/SonicTracer/PinKit'
DIR_PIN_TOOL: '~/project/IgorWork/SonicTracer/PinTool'

DIR_SAVELOGS: '~/project/IgorWork/SonicTracer/logs' #Empty string means not save logs to file and those from Pin will be saved into DIR_FALLBACK.
DIR_FALLBACK: '/tmp'

BIN_nm: '/usr/bin/nm'
BIN_readelf: '/usr/bin/readelf'
BIN_addr2line: '/usr/bin/addr2line'
BIN_llvm-symbolizer: '/usr/lib/llvm-10/bin/llvm-symbolizer'